### ISSUE TITLE
[Bug]: LXC can't create and kubemox pod crashed

### ISSUE THREAD

**Issue by themoriarti** [alperencelik/kubemox#32]
### What happened?

I try create container `lxc1` and container was not created.

Logs from `k logs kubemox-757b8bb74f-458wm`:

```
2024-06-01T23:36:32Z	INFO	Observed a panic in reconciler: 500 Configuration file 'nodes/proxmox1/lxc/101.conf' does not exist	{"controller": "container", "controllerGroup": "proxmox.alperen.cloud", "controllerKind": "Container", "Container": {"name":"lxc1","namespace":"default"}, "namespace": "default", "name": "lxc1", "reconcileID": "baf13aa9-a5c6-44ca-8e7f-fa2a1c55e547"}
panic: 500 Configuration file 'nodes/proxmox1/lxc/101.conf' does not exist [recovered]
	panic: 500 Configuration file 'nodes/proxmox1/lxc/101.conf' does not exist

goroutine 292 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115 +0x1e5
panic({0x16d11c0?, 0xc000d56c10?})
	runtime/panic.go:914 +0x21f
github.com/alperencelik/kubemox/pkg/proxmox.CloneContainer(0xc000ad8400)
	github.com/alperencelik/kubemox/pkg/proxmox/containers.go:23 +0x346
github.com/alperencelik/kubemox/internal/controller/proxmox.(*ContainerReconciler).CloneContainer(0x1b781a8?, 0xc000d66030?)
	github.com/alperencelik/kubemox/internal/controller/proxmox/container_controller.go:163 +0x46
github.com/alperencelik/kubemox/internal/controller/proxmox.(*ContainerReconciler).handleCloneContainer(0xc000b05598?, {0x1b781a8?, 0xc000d66030?}, 0xc000ad8400)
	github.com/alperencelik/kubemox/internal/controller/proxmox/container_controller.go:253 +0x67
github.com/alperencelik/kubemox/internal/controller/proxmox.(*ContainerReconciler).Reconcile(0xc0004bfba8, {0x1b781a8, 0xc000d66030}, {{{0xc000b05584?, 0x0?}, {0xc000b05580?, 0x410a85?}}})
	github.com/alperencelik/kubemox/internal/controller/proxmox/container_controller.go:127 +0x40c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b781a8?, {0x1b781a8?, 0xc000d66030?}, {{{0xc000b05584?, 0x1644620?}, {0xc000b05580?, 0x1b69680?}}})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000243c0, {0x1b781e0, 0xc0003a6f00}, {0x176e9c0?, 0xc000c98880?})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314 +0x368
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000243c0, {0x1b781e0, 0xc0003a6f00})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265 +0x1c9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 43
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x565
```

### What did you expect to happen?

A lxc1 container should have been created

### How can we reproduce it (as minimally and precisely as possible)?

Try to create new LXC container on server where exists old LXC containers used 10X IDs

`kubectl create -f lxc1.yaml`

```
apiVersion: proxmox.alperen.cloud/v1alpha1
kind: Container
metadata:
  name: lxc1
spec:
  name: lxc1
  nodeName: proxmox1
  template:
    name: ubuntu-tpl
    cores: 2
    memory: 4096
    disk: 
      - storage: kvm-disks
        size: 10 
        type: scsi
    network:
      - model: virtio
        bridge: vmbr0
```

### Kubemox version

<details>

```console
v0.0.6-rc2
```

</details>

### Proxmox version

<details>

```console
pve-manager/8.2.2/9355359cd7afbae4 (running kernel: 6.8.4-3-pve)
```

</details>

**Comment by alperencelik** [comment]
Hi @themoriarti, thanks for reporting the issue. I can see that CloneContainer is not implemented properly. I'm working on a fix.

**Comment by alperencelik** [comment]
@themoriarti I just cut a release(v0.0.6-rc3) that includes a fix for the issue. The main is still under development and it has some breaking changes.

**Comment by themoriarti** [comment]
@alperencelik Thx for fast fix.
