### ISSUE TITLE
[Bug]: VirtualMachine network removal is not working properly.

### ISSUE THREAD

**Issue by alperencelik** [alperencelik/kubemox#40]
### What happened?

I've created a VirtualMachine resource without any network configuration but the template had it. The operator failed while trying to remove that network from the new VirtualMachine.

### What did you expect to happen?

I'm expecting program to not break while it's detaching/removing the NIC. It was able to detach the network so functionally it was able to do it's work but then exited which tells me something is not working as expected.

### How can we reproduce it (as minimally and precisely as possible)?

Create a virtual machine template with at least one network. Then apply the VirtualMachine object below:

`
apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachine
metadata:
  name: virtualmachine-sample-clone
spec:
  deletionProtection: false
  enableAutoStart: true
  name: virtualmachine-sample-clone
  nodeName: lowtower
  template:
    cores: 2
    socket: 1
    disk:
    - device: scsi0
      size: 50
      storage: local-lvm
    - device: scsi1
      size: 20
      storage: local-lvm
    memory: 4096
    name: fedora-template
`

### Anything else we need to know?

Here is the log output from the Kubemox for the operation:

`
{"level":"info","ts":"2024-10-17T11:06:42+02:00","msg":"VM virtualmachine-sample-clone updating"}
{"level":"info","ts":"2024-10-17T11:06:58+02:00","msg":"Updating network configuration for VirtualMachine virtualmachine-sample-clone"}
{"level":"info","ts":"2024-10-17T11:06:58+02:00","msg":"Removing the network configuration for net0 of VM virtualmachine-sample-clone"}
panic: runtime error: index out of range [0] with length 0

goroutine 520 [running]:
github.com/alperencelik/kubemox/pkg/proxmox.configureVirtualMachineNetwork(0x140005fcdc8)
        /Users/alperencelik/Desktop/Personal/kubemox/pkg/proxmox/virtualmachine.go:891 +0x610
github.com/alperencelik/kubemox/pkg/proxmox.ConfigureVirtualMachine(0x140005fcdc8)
        /Users/alperencelik/Desktop/Personal/kubemox/pkg/proxmox/virtualmachine.go:806 +0x20
github.com/alperencelik/kubemox/internal/controller/proxmox.(*VirtualMachineReconciler).UpdateVirtualMachine(0x14000400c90, {0x1024b96d0, 0x14001587d10}, 0x140005fcdc8)
        /Users/alperencelik/Desktop/Personal/kubemox/internal/controller/proxmox/virtualmachine_controller.go:311 +0x7c
github.com/alperencelik/kubemox/internal/controller/proxmox.(*VirtualMachineReconciler).Reconcile(0x14000400c90, {0x1024b96d0, 0x14001587d10}, {{{0x1400140f216?, 0x5?}, {0x140013d0900?, 0x14000059d78?}}})
        /Users/alperencelik/Desktop/Personal/kubemox/internal/controller/proxmox/virtualmachine_controller.go:170 +0x264
github.com/alperencelik/kubemox/internal/controller/proxmox.(*VirtualMachineReconciler).handleReconcileFunc(0x14000400c90, {0x1024b96d0, 0x14001587d10}, {0x1024cb030, 0x140005e3348})
        /Users/alperencelik/Desktop/Personal/kubemox/internal/controller/proxmox/virtualmachine_controller.go:357 +0x70
github.com/alperencelik/kubemox/pkg/proxmox.StartWatcher({0x1024b96d0, 0x14001587d10}, {0x1024cb030, 0x140005e3348}, 0x140015271f0, 0x1400059ff38, 0x1400059ff28, 0x1400059ff18, 0x1400059ff08, 0x1400059ff58, ...)
        /Users/alperencelik/Desktop/Personal/kubemox/pkg/proxmox/watcher.go:106 +0x26c
github.com/alperencelik/kubemox/internal/controller/proxmox.(*VirtualMachineReconciler).Reconcile.(*VirtualMachineReconciler).handleWatcher.func1({0x1024b96d0?, 0x14001587d10?}, 0x14000155400?)
        /Users/alperencelik/Desktop/Personal/kubemox/internal/controller/proxmox/virtualmachine_controller.go:335 +0xbc
github.com/alperencelik/kubemox/pkg/proxmox.(*ExternalWatchers).HandleWatcher.func1()
        /Users/alperencelik/Desktop/Personal/kubemox/pkg/proxmox/watcher.go:54 +0x48
created by github.com/alperencelik/kubemox/pkg/proxmox.(*ExternalWatchers).HandleWatcher in goroutine 407
        /Users/alperencelik/Desktop/Personal/kubemox/pkg/proxmox/watcher.go:51 +0x1f4
exit status 2
make: *** [run] Error 1

`

### Kubemox version

<details>

```console
v0.1.2 / latest
```

</details>

### Proxmox version

<details>

```console
pve-manager/8.2.2/9355359cd7afbae4 (running kernel: 6.8.4-2-pve)
```

</details>

**Comment by alperencelik** [comment]
I believe the issue comes from the part of the code below

`		for i := 0; i < len(virtualMachineNetworksParsed); i++ {
			// Check if the network configuration is different
			if !reflect.DeepEqual(networks[i], virtualMachineNetworksParsed[i]) {`
			
The problem here is the we're not controlling whether the len(networks) is zero or not and the comparison is panicing since the networks is empty

**Comment by alperencelik** [comment]
Actually the whole `configureVirtualMachineNetwork()` method logic could be updated for better handling but for now adding another condition to check whether the len(networks) is not equal to zero can fix it.
